/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import control.AcaoCadastroEstrangeiro;
import modelo.ModelCadastroEstrangeiro;

/**
 *
 * @author CarlosFernandes
 */
public class CadastroEstrangeiro extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroEstrangeiro
     */
    private AcaoCadastroEstrangeiro l = new AcaoCadastroEstrangeiro(this);

    public ModelCadastroEstrangeiro modelcdastroestrang() {
        ModelCadastroEstrangeiro modelcadastroest = new ModelCadastroEstrangeiro();

        modelcadastroest.setNome(jtfNomeCompleto.getText());
        modelcadastroest.setEndereco(jtfEdereco.getText());
        modelcadastroest.setNumCelular(jtfNmcelular.getText());
        modelcadastroest.setNumPassaporte(jtfNumPassaport.getText());

        return modelcadastroest;
    }
    public void limpar(){
    jtfNomeCompleto.setText("");
    jtfEdereco.setText("");
    jtfNmcelular.setText("");
    jtfNumPassaport.setText("");
    }

    public CadastroEstrangeiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNumPassaport = new javax.swing.JTextField();
        jtfNomeCompleto = new javax.swing.JTextField();
        jtfNmcelular = new javax.swing.JTextField();
        jtfEdereco = new javax.swing.JTextField();
        jbtSalvar = new javax.swing.JButton();
        jbtlimpar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Nome Completo");

        jLabel2.setText("Endereço");

        jLabel3.setText("Número Passaporte");

        jLabel4.setText("N' Celular");

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        jbtSalvar.addActionListener(l);
        jbtSalvar.setActionCommand("salvar");
        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtlimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/apagar.png"))); // NOI18N
        jbtlimpar.addActionListener(l);
        jbtlimpar.setActionCommand("limpar");
        jbtlimpar.setText("Limpar");
        jbtlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 209, Short.MAX_VALUE)
                        .addComponent(jbtlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNumPassaport)
                            .addComponent(jtfNomeCompleto)
                            .addComponent(jtfNmcelular)
                            .addComponent(jtfEdereco, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNumPassaport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNmcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEdereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtlimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jbtSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtlimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JButton jbtlimpar;
    private javax.swing.JTextField jtfEdereco;
    private javax.swing.JTextField jtfNmcelular;
    private javax.swing.JTextField jtfNomeCompleto;
    private javax.swing.JTextField jtfNumPassaport;
    // End of variables declaration//GEN-END:variables
}
