/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import control.AcaoCadastroFuncionario;
import modelo.ModelCadastroFuncionario;

/**
 *
 * @author CarlosFernandes
 */
public class CadastroFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroFuncionario
     */
    private AcaoCadastroFuncionario l = new AcaoCadastroFuncionario(this);

    public ModelCadastroFuncionario modelcadastro() {
        ModelCadastroFuncionario modelcadastrofunc = new ModelCadastroFuncionario();
        modelcadastrofunc.setEmail(jtfemail.getText());
        modelcadastrofunc.setSenha(jPasswordsenha.getText());
        modelcadastrofunc.setConfsenha(jPasswordConfSenha.getText());
        return modelcadastrofunc;
    }
    
    public void limpar(){
    jtfemail.setText("");
    jPasswordsenha.setText("");
    jPasswordConfSenha.setText("");
    }
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JLabel();
        jtfemail = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        confirmarsenha = new javax.swing.JLabel();
        jbtcadastrar = new javax.swing.JButton();
        jbtlimpar = new javax.swing.JButton();
        jPasswordsenha = new javax.swing.JPasswordField();
        jPasswordConfSenha = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Cadastro de Funcionário");

        email.setText("Email");

        senha.setText("Senha");

        confirmarsenha.setText("Confirmar Senha");

        jbtcadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        jbtcadastrar.setText("Cadastrar");
        jbtcadastrar.addActionListener(l);
        jbtcadastrar.setActionCommand("salvar");
        jbtcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcadastrarActionPerformed(evt);
            }
        });

        jbtlimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/apagar.png"))); // NOI18N
        jbtlimpar.setText("Limpar");
        jbtlimpar.addActionListener(l);
        jbtlimpar.setActionCommand("limpar");
        jbtlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlimparActionPerformed(evt);
            }
        });

        jPasswordConfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordConfSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jbtlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(senha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfemail)
                            .addComponent(jPasswordsenha)
                            .addComponent(jPasswordConfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(email))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(confirmarsenha)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarsenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtcadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtlimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtcadastrarActionPerformed

    private void jPasswordConfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordConfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordConfSenhaActionPerformed

    private void jbtlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtlimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmarsenha;
    private javax.swing.JLabel email;
    private javax.swing.JPasswordField jPasswordConfSenha;
    private javax.swing.JPasswordField jPasswordsenha;
    private javax.swing.JButton jbtcadastrar;
    private javax.swing.JButton jbtlimpar;
    private javax.swing.JTextField jtfemail;
    private javax.swing.JLabel senha;
    // End of variables declaration//GEN-END:variables
}
