/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import control.AcaoRemoveFunc;
import control.DadosControleDb;
import control.DadosControleDbFuncionario;
import exception.Excesao;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import modelo.ModelCadastroEstrangeiro;
import modelo.ModelCadastroFuncionario;
import modelo.ModelChecarFunc;

/**
 *
 * @author CarlosFernandes
 */
public class ChecarFunc extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChecarFunc
     */
    private AcaoRemoveFunc l = new AcaoRemoveFunc(this);

    public ModelChecarFunc getModelChecarFunc() throws Excesao {

        if ("".equals(jtfemail.getText())) {
            throw new Excesao("Deve preencher o email");

        }

        ModelChecarFunc modelchecarfunc = new ModelChecarFunc();
        modelchecarfunc.setEmail(jtfemail.getText());
        return modelchecarfunc;
    }

    public ChecarFunc() {
        initComponents();
        DadosControleDbFuncionario k = new DadosControleDbFuncionario();
        final Vector<ModelCadastroFuncionario> vector = k.getAllVector();
        jtbDados.setModel(new DefaultTableModel() {
            @Override
            public Object getValueAt(int row, int column) {
                ModelCadastroFuncionario item = vector.get(row);
                if (column == 0) {

                    return item.getEmail();
                }
                if (column == 1) {

                    return item.getCpf();
                }
                if (column == 2) {

                    return item.getNome();
                }
                if (column == 3) {

                    return item.getCelular();
                }

                return null;
            }

            @Override
            public int getColumnCount() {
                return 4;//TODO: Ajustar de acordo com o número de colunas
            }

            @Override
            public int getRowCount() {
                return vector.size();
            }

            @Override
            public Vector getDataVector() {
                return vector;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbEmail = new javax.swing.JLabel();
        jtfemail = new javax.swing.JTextField();
        jbtapagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDados = new javax.swing.JTable();

        setClosable(true);

        jlbEmail.setText("Email");

        jbtapagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/apagar.png"))); // NOI18N
        jbtapagar.setText("Apagar");
        jbtapagar.addActionListener(l);
        jbtapagar.setActionCommand("apagar");
        jbtapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtapagarActionPerformed(evt);
            }
        });

        jtbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

                {null},{null},{null},{null},{null}
            },
            new String [] {
                "Email do Funcionário","CPF","Nome","Celular"
            }
        ));
        jScrollPane1.setViewportView(jtbDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfemail)
                        .addGap(18, 18, 18)
                        .addComponent(jbtapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEmail)
                    .addComponent(jtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtapagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtapagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtapagar;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JTable jtbDados;
    private javax.swing.JTextField jtfemail;
    // End of variables declaration//GEN-END:variables
}
