/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import control.AcaoPosLogin;
import javax.swing.JDesktopPane;

/**
 *
 * @author CarlosFernandes
 */
public class PosLogin extends javax.swing.JFrame {

    /**
     * Creates new form PosLogin
     */
    private AcaoPosLogin l = new AcaoPosLogin(this);

    public PosLogin() {
        initComponents();
        setSize(1114, 645);
        setLocationRelativeTo(this);
        setTitle("SIARVE - Agendamento");

    }

    public JDesktopPane getjDesktopPane() {
        return jDesktopPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlbbenvindo = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        jMenuItemNovo = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuIteCadastroFuncionario = new javax.swing.JMenuItem();
        jMenuItemCadastroEstrangeiro = new javax.swing.JMenuItem();
        jMenuchecarCadastro = new javax.swing.JMenu();
        jMenuItemchecarFunc = new javax.swing.JMenuItem();
        jMenuItemchecarAgendamento = new javax.swing.JMenuItem();
        jMenuItemchecarEstr = new javax.swing.JMenuItem();
        menusobre = new javax.swing.JMenu();
        jMenuItemsobre = new javax.swing.JMenuItem();
        menuajuda = new javax.swing.JMenu();
        jMenuItemhelp = new javax.swing.JMenuItem();
        jMenudeveloper = new javax.swing.JMenu();
        jMenuItemdeveloper = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbbenvindo.setBackground(new java.awt.Color(204, 204, 204));
        jlbbenvindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/happiness.png"))); // NOI18N
        jlbbenvindo.setText("  Bem-vindo ao SIARVE");

        menufile.setText("Arquivo");

        jMenuItemNovo.setText("Novo");
        jMenuItemNovo.addActionListener(l);
        jMenuItemNovo.setActionCommand("novo");
        jMenuItemNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovoActionPerformed(evt);
            }
        });
        menufile.add(jMenuItemNovo);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(l);
        jMenuItemSair.setActionCommand("sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        menufile.add(jMenuItemSair);

        jMenuBar1.add(menufile);

        jMenuRegistro.setText("Cadastro ");

        jMenuIteCadastroFuncionario.setText("Cadastro Funcionário");
        jMenuIteCadastroFuncionario.addActionListener(l);
        jMenuIteCadastroFuncionario.setActionCommand("cadastroFuncionario");
        jMenuIteCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIteCadastroFuncionarioActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuIteCadastroFuncionario);

        jMenuItemCadastroEstrangeiro.setText("Cadastro Estrangeiro");
        jMenuItemCadastroEstrangeiro.addActionListener(l);
        jMenuItemCadastroEstrangeiro.setActionCommand("cadastroestrangeiro");
        jMenuItemCadastroEstrangeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroEstrangeiroActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuItemCadastroEstrangeiro);

        jMenuBar1.add(jMenuRegistro);

        jMenuchecarCadastro.setText("Checagem / Remover Funcionário");

        jMenuItemchecarFunc.setText("Remover Funcionário");
        jMenuItemchecarFunc.addActionListener(l);
        jMenuItemchecarFunc.setActionCommand("removerfunc");
        jMenuItemchecarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemchecarFuncActionPerformed(evt);
            }
        });
        jMenuchecarCadastro.add(jMenuItemchecarFunc);

        jMenuItemchecarAgendamento.setText("Checar Agendamento");
        jMenuItemchecarAgendamento.addActionListener(l);
        jMenuItemchecarAgendamento.setActionCommand("checaragendamento");
        jMenuItemchecarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemchecarAgendamentoActionPerformed(evt);
            }
        });
        jMenuchecarCadastro.add(jMenuItemchecarAgendamento);

        jMenuItemchecarEstr.setText("Checar dastro Estrangeiro");
        jMenuItemchecarEstr.addActionListener(l);
        jMenuItemchecarEstr.setActionCommand("checarestr");
        jMenuItemchecarEstr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemchecarEstrActionPerformed(evt);
            }
        });
        jMenuchecarCadastro.add(jMenuItemchecarEstr);

        jMenuBar1.add(jMenuchecarCadastro);

        menusobre.setText("Sobre");
        menusobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusobreActionPerformed(evt);
            }
        });

        jMenuItemsobre.setText("Sobre o Sistema");
        jMenuItemsobre.addActionListener(l);
        jMenuItemsobre.setActionCommand("sobre");
        jMenuItemsobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsobreActionPerformed(evt);
            }
        });
        menusobre.add(jMenuItemsobre);

        jMenuBar1.add(menusobre);

        menuajuda.setText("Ajuda");
        menuajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuajudaActionPerformed(evt);
            }
        });

        jMenuItemhelp.setText("Ajuda");
        jMenuItemhelp.addActionListener(l);
        jMenuItemhelp.setActionCommand("ajuda");
        jMenuItemhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemhelpActionPerformed(evt);
            }
        });
        menuajuda.add(jMenuItemhelp);

        jMenuBar1.add(menuajuda);

        jMenudeveloper.setText("Desenvolvedores");
        jMenudeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenudeveloperActionPerformed(evt);
            }
        });

        jMenuItemdeveloper.setText("Desenvolverdor do Sistema");
        jMenuItemdeveloper.addActionListener(l);
        jMenuItemdeveloper.setActionCommand("developer");
        jMenuItemdeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemdeveloperActionPerformed(evt);
            }
        });
        jMenudeveloper.add(jMenuItemdeveloper);

        jMenuBar1.add(jMenudeveloper);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbbenvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbbenvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemNovoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void menusobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menusobreActionPerformed

    private void menuajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuajudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuajudaActionPerformed

    private void jMenudeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenudeveloperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenudeveloperActionPerformed

    private void jMenuItemsobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemsobreActionPerformed

    private void jMenuItemhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemhelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemhelpActionPerformed

    private void jMenuItemdeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemdeveloperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemdeveloperActionPerformed

    private void jMenuIteCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIteCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuIteCadastroFuncionarioActionPerformed

    private void jMenuItemCadastroEstrangeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroEstrangeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadastroEstrangeiroActionPerformed

    private void jMenuItemchecarEstrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemchecarEstrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemchecarEstrActionPerformed

    private void jMenuItemchecarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemchecarFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemchecarFuncActionPerformed

    private void jMenuItemchecarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemchecarAgendamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemchecarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PosLogin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIteCadastroFuncionario;
    private javax.swing.JMenuItem jMenuItemCadastroEstrangeiro;
    private javax.swing.JMenuItem jMenuItemNovo;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemchecarAgendamento;
    private javax.swing.JMenuItem jMenuItemchecarEstr;
    private javax.swing.JMenuItem jMenuItemchecarFunc;
    private javax.swing.JMenuItem jMenuItemdeveloper;
    private javax.swing.JMenuItem jMenuItemhelp;
    private javax.swing.JMenuItem jMenuItemsobre;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JMenu jMenuchecarCadastro;
    private javax.swing.JMenu jMenudeveloper;
    private javax.swing.JLabel jlbbenvindo;
    private javax.swing.JMenu menuajuda;
    private javax.swing.JMenu menufile;
    private javax.swing.JMenu menusobre;
    // End of variables declaration//GEN-END:variables
}
